# Generated by Django 5.0.7 on 2024-07-13 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='transcripts/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ASSET', 'Asset'), ('EXPENDITURE', 'Expenditure'), ('INCOME', 'Income')], max_length=15)),
                ('fact', models.TextField()),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_info', to='transcripts.transcript')),
            ],
        ),
    ]
